# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'OKEx' do
    # OKEx
    
    pod 'OKFoundation', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKFoundation.git'
    #    pod 'OKFoundation', :path => './component/OKFoundation'
    
    pod 'OKBusiness', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKBusiness.git'
    #    pod 'OKBusiness', :path => './component/OKBusiness'
    
    pod 'OKGHome', :git=>'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGHome.git'
    #    pod 'OKGHome', :path => './component/OKGHome'
    
    pod 'OKGMarket', :git=>'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGMarket.git'
    #    pod 'OKGMarket', :path => './component/OKGMarket'
    
    pod 'OKGSpot', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGSpot.git'
    #     pod 'OKGSpot', :path => './component/OKGSpot'
    
    pod 'OKKLine', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKKLine.git'
    #    pod 'OKKLine', :path => './component/OKKLine'
    
    pod 'OKGAccount', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGAccount.git'
    #    pod 'OKGAccount', :path => './component/OKGAccount'
    
    pod 'OKGKYC', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGKYC.git'
    #    pod 'OKGKYC', :path => './component/OKGKYC'
    
    pod 'OKGCurrency', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGCurrency.git'
    #    pod 'OKGCurrency', :path => './component/OKGCurrency'
    
    pod 'OKGFutures', :git => 'git@gitlab.okcoin-inc.com:OKCoin-iOS/OKGFutures.git'
    #    pod 'OKGFutures', :path => './component/OKGFutures'

    #三方服务

    pod 'AFNetworking',           '3.2.0'
    pod 'Masonry',                '1.1.0'
    pod 'Realm',                  '3.5.0'
    pod 'MJExtension',            '3.0.13'
    pod 'OpenUDID',               '1.0.0'
    pod 'ReactiveObjC',           '3.1.0'
    pod 'YYKit',                  '1.0.9'
    pod 'MJRefresh',              '3.1.15.3'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'IQKeyboardManager',      '6.0.2'
    pod 'lottie-ios',             '2.1.5'
    pod 'SDWebImage',             '4.3.3'
    pod 'MBProgressHUD',          '1.1.0'
    pod 'DZNEmptyDataSet',        '1.8.1'
    pod 'AliyunOSSiOS',           '2.10.4'
    pod 'Bugly',                  '2.5.0'
    pod 'UMengAnalytics',         '4.2.4'

    # 主模块(必须)
    pod 'mob_sharesdk',           '4.1.2'
    
    # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
#    pod 'mob_sharesdk/ShareSDKUI'

    # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
#    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'

end
